//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLibrary.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLibrary.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Name.
        /// </summary>
        public static string AchievementName {
            get {
                return ResourceManager.GetString("AchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Achievements.
        /// </summary>
        public static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Achievements — {0}.
        /// </summary>
        public static string AchievementsFor {
            get {
                return ResourceManager.GetString("AchievementsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Game.
        /// </summary>
        public static string AddGameTitle {
            get {
                return ResourceManager.GetString("AddGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠️ User Management.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Game Library.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Genre.
        /// </summary>
        public static string ByGenre {
            get {
                return ResourceManager.GetString("ByGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Status.
        /// </summary>
        public static string ByStatus {
            get {
                return ResourceManager.GetString("ByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Completed.
        /// </summary>
        public static string CompletedGames {
            get {
                return ResourceManager.GetString("CompletedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete achievement &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmDeleteAchievement {
            get {
                return ResourceManager.GetString("ConfirmDeleteAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmDeleteGame {
            get {
                return ResourceManager.GetString("ConfirmDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ A game with this name already exists.
        /// </summary>
        public static string DuplicateGame {
            get {
                return ResourceManager.GetString("DuplicateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game.
        /// </summary>
        public static string EditGameTitle {
            get {
                return ResourceManager.GetString("EditGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Game Library.
        /// </summary>
        public static string GameLibraryTitle {
            get {
                return ResourceManager.GetString("GameLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} games.
        /// </summary>
        public static string GamesFound {
            get {
                return ResourceManager.GetString("GamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱️ Hours Played.
        /// </summary>
        public static string HoursPlayed {
            get {
                return ResourceManager.GetString("HoursPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Played.
        /// </summary>
        public static string HoursPlayedLabel {
            get {
                return ResourceManager.GetString("HoursPlayedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        public static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 עב.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Leaderboard.
        /// </summary>
        public static string LeaderboardTitle {
            get {
                return ResourceManager.GetString("LeaderboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string LevelAdvanced {
            get {
                return ResourceManager.GetString("LevelAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string LevelBeginner {
            get {
                return ResourceManager.GetString("LevelBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string LevelExpert {
            get {
                return ResourceManager.GetString("LevelExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string LevelIntermediate {
            get {
                return ResourceManager.GetString("LevelIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level (1-5).
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string LevelMaster {
            get {
                return ResourceManager.GetString("LevelMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string LevelUnknown {
            get {
                return ResourceManager.GetString("LevelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Invalid username or password.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚪 Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your game library.
        /// </summary>
        public static string MainPageSubtitle {
            get {
                return ResourceManager.GetString("MainPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account? Register.
        /// </summary>
        public static string NoAccountRegister {
            get {
                return ResourceManager.GetString("NoAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Passwords do not match.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️ Playing Now.
        /// </summary>
        public static string PlayingNow {
            get {
                return ResourceManager.GetString("PlayingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Navigation.
        /// </summary>
        public static string QuickNav {
            get {
                return ResourceManager.GetString("QuickNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating (0-10).
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Registered successfully! Redirecting....
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Register.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠️ Admin.
        /// </summary>
        public static string SidebarAdmin {
            get {
                return ResourceManager.GetString("SidebarAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Home.
        /// </summary>
        public static string SidebarHome {
            get {
                return ResourceManager.GetString("SidebarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 Leaderboard.
        /// </summary>
        public static string SidebarLeaderboard {
            get {
                return ResourceManager.GetString("SidebarLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Library.
        /// </summary>
        public static string SidebarLibrary {
            get {
                return ResourceManager.GetString("SidebarLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Statistics.
        /// </summary>
        public static string SidebarStats {
            get {
                return ResourceManager.GetString("SidebarStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📊 Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Total Games.
        /// </summary>
        public static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Games.
        /// </summary>
        public static string TotalGamesLabel {
            get {
                return ResourceManager.GetString("TotalGamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string TotalHoursLabel {
            get {
                return ResourceManager.GetString("TotalHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Date.
        /// </summary>
        public static string UnlockDate {
            get {
                return ResourceManager.GetString("UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Username already exists.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Username must be at least 3 characters.
        /// </summary>
        public static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Username cannot contain spaces.
        /// </summary>
        public static string UsernameNoSpaces {
            get {
                return ResourceManager.GetString("UsernameNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Value must be 0 or greater.
        /// </summary>
        public static string ValueMustBePositive {
            get {
                return ResourceManager.GetString("ValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Library v1.0 | 2025.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Password is too weak.
        /// </summary>
        public static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
    }
}
